import localFont from "next/font/local";
import "./globals.css";
import DashboardNavbar from "./Components/DashboardNavbar";
import DashboardSideBar from "./Components/DashboardSideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <div className="flex items-start">
         <DashboardSideBar />
         <DashboardNavbar />
       </div>
        {children}
      </body>
    </html>
  );
}
